In [121]:
import numpy as np

In [122]:
x = np.array([[0.05],
              [0.10]])

y = np.array([0.01])
 
print(x)
print(y)
 

[[0.05]
 [0.1 ]]
[0.01]


In [123]:
a0 = x

In [124]:
# Weight matrix for hidden layer (W^{(1)}) – shape (3, 2)
W1 = np.array([[0.15, 0.20],
               [0.25, 0.30],
               [0.35, 0.40]])

In [125]:
# Bias vector for hidden layer (b^{(1)}) – shape (3, 1)
b1 = np.array([[0.35],
               [0.35],
               [0.35]])

In [126]:
# Weight matrix for output layer (W^{(2)}) – shape (1, 3)
W2 = np.array([[0.40, 0.45, 0.50]])

In [127]:
# Bias vector for output layer (b^{(2)}) – shape (1, 1)
b2 = np.array([[0.60]])

In [128]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

## Forward Pass

In [129]:
z1 = W1 @ a0 + b1
a1 = sigmoid(z1)
a1

array([[0.59326999],
       [0.59688438],
       [0.60048827]])

In [130]:
z2 = W2 @ a1 +b2
a2 = sigmoid(z2)
a2

array([[0.803158]])

## Calculate loss

In [131]:
e = a2 - y
loss = 0.5*e.T@e
print(loss)

[[0.31454981]]


## Backward pass

In [132]:
def sigmoid_derivative (z):
    s = sigmoid(z)
    return s * (1 - s)


## Step 1a: Calculate output layer Error Rate 

In [133]:
delta2 = (a2 - y) * sigmoid_derivative(z2)
print("Output layer error delatr2: ", delta2)

Output layer error delatr2:  [[0.12539449]]


## Step 1b : Calculate Hidden Layer Error Rates

In [134]:
delta1 = (W2.T @ delta2) * sigmoid_derivative(z1)
print("Hidden layer error delta1:\n", delta1)

Hidden layer error delta1:
 [[0.01210311]
 [0.01357722]
 [0.0150412 ]]


## Step 2: weight & bias Update

In [135]:
eta = 0.5

In [136]:
W2 = W2 - eta * delta2 @ a1.T      # update weights
b2 = b2 - eta * delta2             # update bias
W2

array([[0.36280361, 0.41257699, 0.46235104]])

In [137]:
W1 = W1 - eta * delta1 @ a0.T      # update weights
b1 = b1 - eta * delta1             # update biases
W1

array([[0.14969742, 0.19939484],
       [0.24966057, 0.29932114],
       [0.34962397, 0.39924794]])